servers:
  - openai_server_engine: vllm
    openai_api_key: token-abc123
  - openai_server_engine: sarathi
    openai_api_key: token-abc123

models:
  - name: mixtral
    identifier: mistralai/Mixtral-8x7B-Instruct-v0.1
    parallel_specs: ["tp_4"]
    traces: null

parallel_specs:
  - name: tp_1
    tp_dimension: 1
    pp_dimension: 1
  - name: tp_8
    tp_dimension: 8
    pp_dimension: 1
  - name: tp_4
    tp_dimension: 4
    pp_dimension: 1

request_generator_configs:
  - start_qps: 1
    request_interval_generator_provider: "poisson"
    request_length_generator_provider: "trace"
    trace_request_length_generator_trace_file: "data/processed_traces/sharegpt_8k_filtered_stats_llama2_tokenizer.csv"
    trace_file_name: "sharegpt"
  - start_qps: 1
    request_interval_generator_provider: "poisson"
    request_length_generator_provider: "trace"
    trace_request_length_generator_trace_file: "data/processed_traces/arxiv_summarization_filtered_stats_llama2_tokenizer.csv"
    trace_file_name: "arxiv"

request_configs:
  - num_ray_clients: 10
    num_concurrent_requests_per_client: 10
    timeout: 1200
    max_num_completed_requests: 1000
    additional_sampling_params: {}
    llm_api: "openai"
    request_generator_max_tokens: 16384
