name: 🛠️ Installation
description: Report an issue here when you hit errors during installation.
title: "[Installation]: "
labels: ["installation"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/project-etalon/etalon/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: Your current environment
    description: |
      Please describe the environment you are running with including OS distribution and Python versions.
  validations:
    required: true
- type: textarea
  attributes:
    label: How you are installing etalon
    description: |
      Paste the full command you are trying to execute.
    value: |
      ```sh
      pip install -vvv etalon
      ```
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
