import abc
from typing import Tuple

from metron.core.hf_utils import get_tokenizer
from metron.core.request_config import RequestConfig
from metron.metrics.request_metrics import RequestMetrics


class BaseLLMClient:
    """A client for making requests to a LLM API e.g Anyscale Endpoints."""

    def __init__(self, model_name: str) -> None:
        self.tokenizer = get_tokenizer(
            model_name,
            trust_remote_code=True,
        )

    def get_token_length(self, text: str) -> int:
        return len(self.tokenizer.encode(text))

    async def send_llm_request(
        self, request_config: RequestConfig
    ) -> Tuple[RequestMetrics, str]:
        request_metrics, generated_text = await self.send_llm_request_(request_config)
        return request_metrics, generated_text

    @abc.abstractmethod
    async def send_llm_request_(
        self, request_config: RequestConfig
    ) -> Tuple[RequestMetrics, str]:
        """Make a single completion request to a LLM API

        Returns:
            Metrics about the performance charateristics of the request.
            The text generated by the request to the LLM API.
        """
        ...
