name: "Run linter"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash -l {0}
jobs:
  sanity_check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: "Install dependencies"
        run: pip install -r requirements-dev.txt
      - name: "Run black lint"
        run: make lint/black
      - name: "Run isort check"
        run: make lint/isort
